import { faBox, faBoxes, faChartLine, faChartPie, faPercent, faReceipt, faUsers, faUserTie } from '@fortawesome/free-solid-svg-icons'

export const mainSidebars = [
    {
        type: 'item',
        url: route('overview'),
        icon: faChartPie,
        label: 'Ringkasan',
        permissions: [],
        activeRoute: 'overview',
    },
    {
        type: 'dropdown',
        url: '#',
        icon: faChartLine,
        label: 'Laporan',
        permissions: [],
        activeRoute: 'reports',
        items: [
            {
                type: 'item',
                url: route('reports.sales.index'),
                label: 'Laporan Penjualan',
                permissions: ['report.sales.view'],
                activeRoute: 'reports.sales.',
            },
            {
                type: 'item',
                url: route('reports.products.index'),
                label: 'Laporan Produk',
                permissions: ['report.product.view'],
                activeRoute: 'reports.products.',
            },
            {
                type: 'item',
                url: route('reports.stocks.index'),
                label: 'Laporan Stock & Aset',
                permissions: ['report.stock.view'],
                activeRoute: 'reports.stocks.',
            },
            {
                type: 'item',
                url: route('reports.cashiers.index'),
                label: 'Laporan Shift & Kas',
                permissions: ['report.cashier.view'],
                activeRoute: 'reports.cashiers.',
            },
            {
                type: 'item',
                url: route('reports.promotions.index'),
                label: 'Laporan Promo',
                permissions: ['report.promotion.view'],
                activeRoute: 'reports.promotions.',
            },
            {
                type: 'item',
                url: route('reports.customers.index'),
                label: 'Laporan Pelanggan',
                permissions: ['report.customer.view'],
                activeRoute: 'reports.customers.',
            },
        ],
    },
    {
        type: 'dropdown',
        url: '#',
        icon: faReceipt,
        label: 'Transaksi',
        permissions: ['transaction.view'],
        activeRoute: 'transactions',
        items: [
            {
                type: 'item',
                url: route('transactions.sales.index'),
                label: 'Penjualan',
                permissions: ['transaction.view'],
                activeRoute: 'transactions.sales.',
            },
            {
                type: 'item',
                url: route('transactions.shifts.index'),
                label: 'Shift Kasir',
                permissions: ['transaction.view'],
                activeRoute: 'transactions.shifts.',
            },
        ]
    },
    {
        type: 'dropdown',
        url: '#',
        icon: faBox,
        label: 'Master Produk',
        permissions: [],
        activeRoute: 'master.',
        items: [
            {
                type: 'item',
                url: route('master.categories.index'),
                label: 'Kategori Produk',
                permissions: [],
                activeRoute: 'master.categories.',
            },
            {
                type: 'item',
                url: route('master.products.index'),
                label: 'Produk',
                permissions: [],
                activeRoute: 'master.products.',
            },
            // {
            //     type: 'item',
            //     url: route('master.modifiers.index'),
            //     label: 'Opsi Tambahan',
            //     permissions: [],
            //     activeRoute: 'master.modifiers.',
            // },
        ],
    },
    {
        type: 'dropdown',
        url: '#',
        icon: faBoxes,
        label: 'Inventori',
        permissions: [],
        activeRoute: 'inventories.',
        items: [
            // {
            //     type: 'item',
            //     url: route('inventory.raw-materials.index'),
            //     label: 'Bahan Baku',
            //     permissions: [],
            //     activeRoute: 'inventory.raw-materials.',
            // },
            {
                type: 'item',
                url: route('inventories.stocks.index'),
                label: 'Stok',
                permissions: [],
                activeRoute: 'inventories.stocks.',
            },
            {
                type: 'item',
                url: route('inventory.suppliers.index'),
                label: 'Pemasok / Supplier',
                permissions: [],
                activeRoute: 'inventory.suppliers.',
            },
            {
                type: 'item',
                url: route('inventory.purchases.index'),
                label: 'Pembelian (PO)',
                permissions: [],
                activeRoute: 'inventory.purchases.',
            },
            {
                type: 'item',
                url: route('inventory.adjustments.index'),
                label: 'Penyesuaian Stok',
                permissions: [],
                activeRoute: 'inventory.adjustments.',
            },
            {
                type: 'item',
                url: route('inventory.opnames.index'),
                label: 'Stok Opname',
                permissions: [],
                activeRoute: 'inventory.opnames.',
            },
            {
                type: 'item',
                url: route('inventory.transfers.index'),
                label: 'Mutasi Stok',
                permissions: [],
                activeRoute: 'inventory.transfers.',
            },
        ],
    },
    {
        type: 'item',
        url: route('promotions.index'),
        icon: faPercent,
        label: 'Promosi',
        permissions: [],
        activeRoute: 'promotions',
    },
    {
        type: 'item',
        url: route('customers.index'),
        icon: faUsers,
        label: 'Pelanggan',
        permissions: [],
        activeRoute: 'customers',
    },
    {
        type: 'item',
        url: route('employees.index'),
        icon: faUserTie,
        label: 'Pegawai',
        permissions: ['user.view'],
        activeRoute: 'employees',
    },

    // {
    //     type: 'dropdown',
    //     url: '#',
    //     icon: faHashtag,
    //     label: 'Template',
    //     permissions: [],
    //     activeRoute: 'template',
    //     items: [
    //         {
    //             type: 'item',
    //             url: route('template.form'),
    //             label: 'Form',
    //             permissions: [],
    //             activeRoute: 'template.form',
    //         },
    //         {
    //             type: 'item',
    //             url: route('template.cards'),
    //             label: 'Card',
    //             permissions: [],
    //             activeRoute: 'template.cards',
    //         },
    //         {
    //             type: 'item',
    //             url: route('template.navigation'),
    //             label: 'Navigation & Tab',
    //             permissions: [],
    //             activeRoute: 'template.navigation',
    //         },
    //         {
    //             type: 'item',
    //             url: route('template.buttons'),
    //             label: 'Buttons',
    //             permissions: [],
    //             activeRoute: 'template.buttons',
    //         },
    //         {
    //             type: 'item',
    //             url: route('template.charts'),
    //             label: 'Charts',
    //             permissions: [],
    //             activeRoute: 'template.charts',
    //         },
    //         {
    //             type: 'item',
    //             url: route('template.notifications'),
    //             label: 'Notifications',
    //             permissions: [],
    //             activeRoute: 'template.notifications',
    //         },
    //         {
    //             type: 'item',
    //             url: route('template.widgets'),
    //             label: 'Widgets',
    //             permissions: [],
    //             activeRoute: 'template.widgets',
    //         },
    //     ],
    // },
]
